#!/bin/bash

echo -e "\nChecking load balancing, session cookie\n"

for i in {0..13}
do
	curl -v https://apache-shiny-demo.herokuapp.com/ 2>&1 | grep Set-Cookie
done

echo -e "\nChecking process ID\n"

for i in {0..13}
do
	curl -s https://apache-shiny-demo.herokuapp.com/ | grep "Process Id"
done

# using https://github.com/wg/wrk utility
# echo -e "\nLoad test\n"
# wrk -t12 -c400 -d30s https://apache-shiny-demo.herokuapp.com/
